/* ============================================================
   Base de ejercicios + rutina de hipertrofia (4 días, sin abdomen)
   Imágenes: free-exercise-db (2 frames -> se animan tipo GIF)
   ============================================================ */

const APP_VERSION = 'v17 · barco ligas cerradas';
const RAW = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';
function frames(id) { return [RAW + id + '/0.jpg', RAW + id + '/1.jpg']; }
function yt(name) { return 'https://www.youtube.com/results?search_query=' + encodeURIComponent('como hacer ' + name + ' tecnica'); }

/* Diccionario de ejercicios. clave = id de la base de imágenes.
   es = nombre en español · musc = músculo · equip = equipo
   setup = cómo configurar la máquina/preparar · tip = técnica clave */
const EX = {
  // ---------- PECHO ----------
  'Barbell_Bench_Press_-_Medium_Grip': { es:'Press de banca con barra', musc:'Pecho', equip:'Barra',
    setup:'Acostate en el banco plano con los ojos debajo de la barra. Pies firmes en el piso, espalda con un leve arco. Agarre un poco más ancho que los hombros.',
    tip:'Bajá la barra al centro del pecho tocando suave, codos a ~45°. Empujá sin rebotar.' },
  'Dumbbell_Bench_Press': { es:'Press de banca con mancuernas', musc:'Pecho', equip:'Mancuernas',
    setup:'Banco plano. Sentate con las mancuernas sobre los muslos y recostate impulsándolas a la posición inicial, a la altura del pecho.',
    tip:'Bajá hasta sentir estiramiento en el pecho, subí juntando arriba sin chocar las mancuernas.' },
  'Machine_Bench_Press': { es:'Press de pecho en máquina', musc:'Pecho', equip:'Máquina',
    setup:'Ajustá el asiento para que las manijas queden a la altura del pecho medio. Espalda apoyada en el respaldo.',
    tip:'Empujá al frente estirando casi del todo y volvé despacio controlando.' },
  'Incline_Dumbbell_Press': { es:'Press inclinado con mancuernas', musc:'Pecho superior', equip:'Mancuernas',
    setup:'Regulá el banco a 30–45°. Apoyá bien la espalda, mancuernas a la altura de la parte alta del pecho.',
    tip:'Empujá hacia arriba y adentro. No inclines demasiado el banco para no cargar hombros.' },
  'Butterfly': { es:'Contractora / Pec deck', musc:'Pecho', equip:'Máquina',
    setup:'Ajustá el asiento para que las manijas queden a la altura de los hombros. Espalda pegada al respaldo.',
    tip:'Juntá los codos al frente apretando el pecho, volvé lento sintiendo el estiramiento.' },
  'Cable_Crossover': { es:'Cruce de poleas', musc:'Pecho', equip:'Poleas',
    setup:'Colocá ambas poleas en alto. Agarrá una manija en cada mano y da un paso al frente con el torso levemente inclinado.',
    tip:'Cruzá las manos abajo y al centro apretando el pecho. Movimiento de abrazo.' },
  'Dumbbell_Flyes': { es:'Aperturas con mancuernas', musc:'Pecho', equip:'Mancuernas',
    setup:'Banco plano, mancuernas arriba del pecho con codos apenas flexionados.',
    tip:'Abrí en arco hasta la altura del pecho, subí juntando. No bajes de más.' },

  // ---------- TRÍCEPS ----------
  'Triceps_Pushdown': { es:'Extensión de tríceps en polea (barra)', musc:'Tríceps', equip:'Polea alta',
    setup:'Polea en alto con barra recta. Codos pegados al cuerpo, dá un paso atrás.',
    tip:'Estirá los codos hacia abajo del todo, subí sin despegar los codos.' },
  'Triceps_Pushdown_-_Rope_Attachment': { es:'Extensión de tríceps en polea (cuerda)', musc:'Tríceps', equip:'Polea alta',
    setup:'Polea en alto con cuerda. Codos al costado del torso.',
    tip:'Al final abrí la cuerda hacia afuera para apretar más el tríceps.' },
  'Cable_Rope_Overhead_Triceps_Extension': { es:'Extensión de tríceps sobre la cabeza (cuerda)', musc:'Tríceps', equip:'Polea',
    setup:'Polea baja o media con cuerda. Dá la espalda a la polea, cuerda por detrás de la cabeza, codos apuntando al frente.',
    tip:'Estirá hacia adelante-arriba. Mantené los codos quietos y altos.' },
  'EZ-Bar_Skullcrusher': { es:'Rompecráneos con barra Z', musc:'Tríceps', equip:'Barra Z',
    setup:'Banco plano, barra Z sobre el pecho con brazos estirados.',
    tip:'Bajá la barra hacia la frente flexionando solo los codos, luego estirá.' },
  'Standing_Dumbbell_Triceps_Extension': { es:'Extensión de tríceps con mancuerna', musc:'Tríceps', equip:'Mancuerna',
    setup:'De pie o sentado, una mancuerna con ambas manos por detrás de la cabeza.',
    tip:'Codos altos y quietos. Estirá hacia arriba controlando la bajada.' },
  'Reverse_Grip_Triceps_Pushdown': { es:'Extensión de tríceps agarre invertido', musc:'Tríceps', equip:'Polea alta',
    setup:'Polea en alto con barra recta, agarre con palmas hacia arriba (supino).',
    tip:'Foco en la cabeza interna del tríceps. Codos pegados al cuerpo.' },

  // ---------- ESPALDA ----------
  'Wide-Grip_Lat_Pulldown': { es:'Jalón al pecho agarre ancho', musc:'Espalda (dorsales)', equip:'Polea alta',
    setup:'Ajustá la rodillera para que las piernas queden fijas. Agarre ancho de la barra, palmas al frente.',
    tip:'Llevá la barra al pecho alto sacando pecho, codos hacia abajo. Volvé estirando bien.' },
  'Close-Grip_Front_Lat_Pulldown': { es:'Jalón al pecho agarre cerrado', musc:'Espalda (dorsales)', equip:'Polea alta',
    setup:'Ajustá la rodillera. Usá el triángulo o agarre angosto.',
    tip:'Tirá al pecho apretando la espalda media. Pecho arriba.' },
  'Seated_Cable_Rows': { es:'Remo sentado en polea', musc:'Espalda', equip:'Polea baja',
    setup:'Sentate con pies en los apoyos y rodillas semiflexionadas. Agarrá el triángulo con la espalda recta.',
    tip:'Tirá hacia el abdomen juntando los omóplatos. No uses impulso de la espalda baja.' },
  'Bent_Over_Barbell_Row': { es:'Remo con barra inclinado', musc:'Espalda', equip:'Barra',
    setup:'De pie, tronco inclinado ~45°, espalda recta, rodillas semiflexionadas. Barra colgando.',
    tip:'Tirá la barra al ombligo/abdomen bajo, codos hacia atrás. Bajá controlando.' },
  'Bent_Over_Two-Dumbbell_Row': { es:'Remo con mancuernas inclinado', musc:'Espalda', equip:'Mancuernas',
    setup:'Tronco inclinado con espalda recta, una mancuerna en cada mano colgando.',
    tip:'Remá ambas mancuernas hacia la cadera apretando la espalda.' },

  // ---------- BÍCEPS ----------
  'Barbell_Curl': { es:'Curl de bíceps con barra', musc:'Bíceps', equip:'Barra',
    setup:'De pie, barra con agarre a la anchura de hombros, palmas al frente. Codos pegados al torso.',
    tip:'Subí sin balancear el cuerpo, apretá arriba y bajá lento.' },
  'EZ-Bar_Curl': { es:'Curl con barra Z', musc:'Bíceps', equip:'Barra Z',
    setup:'De pie con barra Z, agarre en las curvas (más cómodo para las muñecas).',
    tip:'Codos quietos. Subí y bajá sin usar impulso.' },
  'Hammer_Curls': { es:'Curl martillo', musc:'Bíceps / Antebrazo', equip:'Mancuernas',
    setup:'De pie, mancuernas a los costados con agarre neutro (palmas enfrentadas).',
    tip:'Subí como si martillaras, muñeca firme. Trabaja el braquial y antebrazo.' },
  'Alternate_Hammer_Curl': { es:'Curl martillo alternado', musc:'Bíceps / Antebrazo', equip:'Mancuernas',
    setup:'De pie, agarre neutro, alternás un brazo por vez.',
    tip:'Controlá la bajada de cada brazo. Sin balanceo del torso.' },
  'Cable_Hammer_Curls_-_Rope_Attachment': { es:'Curl martillo en polea (cuerda)', musc:'Bíceps', equip:'Polea baja',
    setup:'Polea baja con cuerda, agarre neutro. Codos pegados al cuerpo.',
    tip:'Tensión constante: no aflojes abajo. Apretá arriba.' },

  // ---------- PIERNAS ----------
  'Barbell_Squat': { es:'Sentadilla con barra', musc:'Cuádriceps / Glúteos', equip:'Barra + rack',
    setup:'Ajustá el rack a la altura del pecho. Barra apoyada sobre los trapecios, pies a la anchura de hombros, puntas levemente afuera.',
    tip:'Bajá sacando la cola atrás hasta que los muslos queden paralelos. Rodillas siguiendo la punta de los pies.' },
  'Leg_Press': { es:'Prensa de piernas', musc:'Cuádriceps / Glúteos', equip:'Máquina',
    setup:'Sentate con la espalda y cola bien apoyadas. Pies en la plataforma a la anchura de hombros, media altura.',
    tip:'Bajá hasta ~90° sin despegar la cola. Empujá con los talones sin bloquear de golpe las rodillas.' },
  'Narrow_Stance_Leg_Press': { es:'Prensa pies juntos', musc:'Cuádriceps', equip:'Máquina',
    setup:'Igual que la prensa pero con los pies juntos y bajos en la plataforma.',
    tip:'Mayor foco en el cuádriceps externo. Rango completo y controlado.' },
  'Leg_Extensions': { es:'Extensión de cuádriceps', musc:'Cuádriceps', equip:'Máquina',
    setup:'Espalda contra el respaldo. Ajustá el rodillo para que quede sobre los tobillos y el eje a la altura de la rodilla.',
    tip:'Estirá las piernas apretando el cuádriceps arriba, bajá lento.' },
  'Lying_Leg_Curls': { es:'Curl femoral acostado', musc:'Femoral', equip:'Máquina',
    setup:'Boca abajo, rodillo sobre la parte de atrás de los tobillos, eje a la altura de la rodilla.',
    tip:'Llevá los talones a la cola apretando el femoral. Bajá controlando.' },
  'Seated_Leg_Curl': { es:'Curl femoral sentado', musc:'Femoral', equip:'Máquina',
    setup:'Sentate con el rodillo sobre la parte baja de las pantorrillas y el apoyo sobre los muslos.',
    tip:'Flexioná llevando los talones hacia abajo-atrás. Apretá y volvé lento.' },
  'Romanian_Deadlift': { es:'Peso muerto rumano', musc:'Femoral / Glúteos', equip:'Barra',
    setup:'De pie con la barra pegada a los muslos, agarre a la anchura de hombros, rodillas apenas flexionadas.',
    tip:'Llevá la cola atrás bajando la barra pegada a las piernas hasta sentir el femoral. Espalda recta siempre.' },
  'Standing_Calf_Raises': { es:'Elevación de gemelos de pie', musc:'Gemelos', equip:'Máquina',
    setup:'Hombros bajo las almohadillas, punta de los pies en la plataforma, talones al aire.',
    tip:'Subí lo más alto posible en punta de pie, bajá estirando bien el gemelo.' },
  'Calf_Press': { es:'Gemelos en prensa', musc:'Gemelos', equip:'Máquina',
    setup:'En la prensa, apoyá solo la punta de los pies en el borde inferior de la plataforma.',
    tip:'Empujá con las puntas estirando el tobillo, volvé estirando el gemelo. No bloquees rodillas.' },

  // ---------- HOMBROS ----------
  'Dumbbell_Shoulder_Press': { es:'Press de hombros con mancuernas', musc:'Hombros', equip:'Mancuernas',
    setup:'Sentate con respaldo. Mancuernas a la altura de las orejas, codos abajo.',
    tip:'Empujá arriba sin bloquear de golpe. Bajá controlando hasta las orejas.' },
  'Standing_Dumbbell_Press': { es:'Press militar de pie con mancuernas', musc:'Hombros', equip:'Mancuernas',
    setup:'De pie, abdomen firme, mancuernas a la altura de los hombros.',
    tip:'Empujá arriba sin arquear la espalda baja. Core apretado.' },
  'Smith_Machine_Overhead_Shoulder_Press': { es:'Press de hombros en máquina Smith', musc:'Hombros', equip:'Smith',
    setup:'Banco con respaldo bajo la barra del Smith, barra a la altura de la clavícula.',
    tip:'Empujá recto arriba y bajá controlando. Ideal para empezar con más seguridad.' },
  'Side_Lateral_Raise': { es:'Elevaciones laterales', musc:'Hombro lateral', equip:'Mancuernas',
    setup:'De pie, mancuernas a los costados, codos apenas flexionados.',
    tip:'Subí a los costados hasta la altura de los hombros, meñiques un poco arriba. Bajá lento.' },
  'Front_Dumbbell_Raise': { es:'Elevaciones frontales', musc:'Hombro anterior', equip:'Mancuernas',
    setup:'De pie, mancuernas apoyadas al frente de los muslos.',
    tip:'Subí al frente hasta la altura de los ojos, sin impulso. Alterná o juntas.' },
  'Face_Pull': { es:'Face pull (jalón a la cara)', musc:'Hombro posterior', equip:'Polea alta',
    setup:'Polea a la altura de la cara con cuerda. Dá un paso atrás y agarrá con palmas hacia adentro.',
    tip:'Tirá hacia la frente abriendo la cuerda, codos altos. Apretá la parte de atrás del hombro.' },
  'Reverse_Machine_Flyes': { es:'Aperturas invertidas en máquina', musc:'Hombro posterior', equip:'Máquina',
    setup:'Sentate mirando la máquina (pecho contra el respaldo). Manijas al frente a la altura de los hombros.',
    tip:'Abrí los brazos hacia atrás apretando la parte posterior del hombro.' },
  'Cable_Rear_Delt_Fly': { es:'Aperturas posteriores en polea', musc:'Hombro posterior', equip:'Poleas',
    setup:'Poleas cruzadas a la altura de los hombros, agarrás la manija opuesta con cada mano.',
    tip:'Abrí en cruz hacia atrás, sin usar la espalda. Foco en el deltoides posterior.' },

  // ========== EN CASA / VIAJE (bandas, pelota, mancuernas livianas) ==========
  'Pushups': { es:'Flexiones', musc:'Pecho', equip:'Peso corporal',
    setup:'En el piso, manos un poco más anchas que los hombros, cuerpo en línea recta.',
    tip:'Bajá el pecho casi al piso, codos a ~45°, subí sin arquear la cintura. Podés apoyar las rodillas.' },
  'Bench_Press_-_With_Bands': { es:'Press de pecho con banda', musc:'Pecho', equip:'Banda',
    setup:'Pasá la banda por detrás de la espalda, un extremo en cada mano a la altura del pecho.',
    tip:'Empujá al frente estirando los brazos, volvé controlando la tensión de la banda.' },
  'Band_Skull_Crusher': { es:'Rompecráneos con banda', musc:'Tríceps', equip:'Banda',
    setup:'Fijá la banda atrás (o pisala); agarrá los extremos con las manos detrás de la cabeza.',
    tip:'Estirá los codos hacia adelante-arriba, mantené los codos quietos.' },
  'Tricep_Dumbbell_Kickback': { es:'Patada de tríceps con mancuerna', musc:'Tríceps', equip:'Mancuernas',
    setup:'Tronco inclinado al frente, codo pegado al costado y flexionado 90°.',
    tip:'Estirá el brazo hacia atrás apretando el tríceps, sin mover el codo.' },
  'One-Arm_Dumbbell_Row': { es:'Remo a un brazo con mancuerna', musc:'Espalda', equip:'Mancuernas',
    setup:'Apoyá una rodilla y una mano en una silla o cama, espalda recta, mancuerna colgando.',
    tip:'Remá la mancuerna hacia la cadera, codo pegado. Bajá controlando.' },
  'Band_Pull_Apart': { es:'Aperturas con banda (pull apart)', musc:'Espalda alta / Hombro posterior', equip:'Banda',
    setup:'De pie, brazos al frente a la altura del pecho. Con banda larga sostené los extremos; con liga cerrada chiquita pasala alrededor de las muñecas.',
    tip:'Abrí los brazos separando la banda y juntando los omóplatos. Volvé lento.' },
  'Bent-Arm_Dumbbell_Pullover': { es:'Pullover con mancuerna', musc:'Espalda / Pecho', equip:'Mancuernas',
    setup:'Acostada (en el piso o sobre la pelota), una mancuerna con ambas manos sobre el pecho.',
    tip:'Llevá la mancuerna por detrás de la cabeza estirando, y volvé al pecho.' },
  'Dumbbell_Bicep_Curl': { es:'Curl de bíceps con mancuernas', musc:'Bíceps', equip:'Mancuernas',
    setup:'De pie, mancuernas a los costados, palmas al frente.',
    tip:'Subí sin balancear, apretá arriba y bajá lento.' },
  'Dumbbell_Squat': { es:'Sentadilla con mancuernas', musc:'Cuádriceps / Glúteos', equip:'Mancuernas',
    setup:'De pie, mancuernas a los costados o sobre los hombros, pies a la anchura de hombros.',
    tip:'Bajá sacando la cola hasta muslos paralelos, subí empujando con los talones.' },
  'Dumbbell_Lunges': { es:'Zancadas con mancuernas', musc:'Cuádriceps / Glúteos', equip:'Mancuernas',
    setup:'De pie con mancuernas a los costados, dá un paso largo al frente.',
    tip:'Bajá la rodilla de atrás casi al piso con el tronco recto. Alterná piernas.' },
  'Stiff-Legged_Dumbbell_Deadlift': { es:'Peso muerto rumano con mancuernas', musc:'Femoral / Glúteos', equip:'Mancuernas',
    setup:'De pie, mancuernas al frente de los muslos, rodillas apenas flexionadas.',
    tip:'Llevá la cola atrás bajando las mancuernas pegadas a las piernas. Espalda recta.' },
  'Plie_Dumbbell_Squat': { es:'Sentadilla sumo con mancuerna', musc:'Glúteos / Aductores', equip:'Mancuernas',
    setup:'Pies anchos con las puntas hacia afuera, una mancuerna sostenida entre las piernas.',
    tip:'Bajá recto entre los talones, apretá los glúteos al subir.' },
  'Single_Leg_Glute_Bridge': { es:'Puente de glúteo a una pierna', musc:'Glúteos', equip:'Peso corporal',
    setup:'Boca arriba, una pierna flexionada apoyada y la otra estirada.',
    tip:'Subí la cadera apretando el glúteo de la pierna de apoyo. Alterná.' },
  'Physioball_Hip_Bridge': { es:'Puente de cadera en pelota', musc:'Glúteos / Femoral', equip:'Pelota de pilates',
    setup:'Hombros apoyados en la pelota, pies en el piso, cadera abajo.',
    tip:'Subí la cadera hasta alinear el cuerpo y apretá glúteos. Estabilizá la pelota.' },
  'Butt_Lift_Bridge': { es:'Puente de glúteos', musc:'Glúteos', equip:'Peso corporal',
    setup:'Boca arriba, rodillas flexionadas, pies apoyados cerca de la cola.',
    tip:'Subí la cadera apretando glúteos, pausá arriba. Podés apoyar una mancuerna encima.' },
  'Squats_-_With_Bands': { es:'Sentadilla con banda', musc:'Cuádriceps / Glúteos', equip:'Liga cerrada',
    setup:'Liga cerrada arriba de las rodillas. Pies a la anchura de los hombros, empujando ligero hacia afuera.',
    tip:'Sentadilla normal cuidando que las rodillas no se metan hacia adentro contra la liga.' },
  'Hip_Extension_with_Bands': { es:'Extensión de cadera con banda', musc:'Glúteos', equip:'Liga cerrada',
    setup:'Liga cerrada arriba de los tobillos. De pie, sujetate de algo firme.',
    tip:'Llevá la pierna hacia atrás apretando el glúteo, sin arquear la espalda. Alterná.' },
  'Calf_Raises_-_With_Bands': { es:'Elevación de gemelos', musc:'Gemelos', equip:'Peso corporal',
    setup:'De pie, punta de los pies en el piso o en un borde/escalón, talones al aire.',
    tip:'Subí lo más alto posible en puntas de pie, bajá estirando bien el gemelo. Hacelas lento.' },
  'Arnold_Dumbbell_Press': { es:'Press Arnold', musc:'Hombros', equip:'Mancuernas',
    setup:'Sentada, mancuernas al frente con las palmas hacia vos.',
    tip:'Girá las palmas al frente mientras empujás hacia arriba. Volvé girando.' },
  'Seated_Side_Lateral_Raise': { es:'Elevaciones laterales sentada', musc:'Hombro lateral', equip:'Mancuernas',
    setup:'Sentada, mancuernas a los costados, codos apenas flexionados.',
    tip:'Subí a los costados hasta la altura de los hombros. Bajá lento.' },
  'One-Arm_Side_Laterals': { es:'Elevación lateral a un brazo', musc:'Hombro lateral', equip:'Mancuernas',
    setup:'De pie, sujetate con una mano, mancuerna en la otra.',
    tip:'Subí la mancuerna al costado hasta la altura del hombro. Alterná.' },
  'Lateral_Raise_-_With_Bands': { es:'Elevaciones laterales con banda', musc:'Hombro lateral', equip:'Banda',
    setup:'Pisá la banda con un pie y agarrá los extremos a los costados.',
    tip:'Subí los brazos a los costados contra la banda. Controlá la bajada.' },
  'Reverse_Flyes': { es:'Aperturas invertidas con mancuernas', musc:'Hombro posterior', equip:'Mancuernas',
    setup:'Tronco inclinado al frente, mancuernas colgando, codos apenas flexionados.',
    tip:'Abrí los brazos hacia atrás apretando la parte de atrás del hombro.' },

  // ========== BARCO · LIGAS CERRADAS CHIQUITAS (tipo pilates) + PESO CORPORAL ==========
  'Incline_Push-Up': { es:'Flexiones inclinadas', musc:'Pecho superior', equip:'Peso corporal',
    setup:'Manos sobre una superficie elevada (banco, borde, escalón), cuerpo en línea recta.',
    tip:'Bajá el pecho a la superficie y empujá. Cuanto más alta la superficie, más fácil.' },
  'Close-Grip_Push-Up_off_of_a_Dumbbell': { es:'Flexiones diamante (cerradas)', musc:'Tríceps / Pecho interno', equip:'Peso corporal',
    setup:'En el piso, manos juntas debajo del pecho (índices y pulgares casi tocándose).',
    tip:'Bajá con los codos pegados al cuerpo y empujá. Trabaja mucho el tríceps. Podés apoyar rodillas.' },
  'Bench_Dips': { es:'Fondos de tríceps en banco', musc:'Tríceps', equip:'Peso corporal',
    setup:'Manos en el borde de un banco/silla detrás tuyo, piernas al frente.',
    tip:'Bajá flexionando los codos hacia atrás y empujá. Estirá las piernas para más dificultad.' },
  'Handstand_Push-Ups': { es:'Flexiones pica / hombros', musc:'Hombros', equip:'Peso corporal',
    setup:'Versión fácil (pica): cadera arriba en “V” invertida con las manos en el piso y la cabeza apuntando abajo. No hace falta pararte de manos.',
    tip:'Bajá la cabeza hacia el piso flexionando los codos y empujá arriba. Cuanto más vertical la cadera, más peso en el hombro.' },
  'Superman': { es:'Superman (espalda baja)', musc:'Espalda baja / Glúteos', equip:'Peso corporal',
    setup:'Boca abajo, brazos estirados al frente y piernas estiradas.',
    tip:'Elevá al mismo tiempo brazos, pecho y piernas apretando la espalda y los glúteos. Pausá arriba.' },
  'Hyperextensions_With_No_Hyperextension_Bench': { es:'Extensión de espalda en el piso', musc:'Espalda baja / Glúteos', equip:'Peso corporal',
    setup:'Boca abajo, manos en las sienes o cruzadas en el pecho.',
    tip:'Elevá el pecho del piso apretando la espalda baja y los glúteos, bajá controlando. Sin tirones.' },
  'External_Rotation_with_Band': { es:'Rotación externa con banda', musc:'Hombro posterior / Manguito', equip:'Liga cerrada',
    setup:'Codos pegados al cuerpo y flexionados 90°, la liga cerrada chiquita alrededor de las dos muñecas.',
    tip:'Abrí las manos hacia afuera contra la liga sin despegar los codos. Volvé lento.' },
  'Bodyweight_Squat': { es:'Sentadilla libre', musc:'Cuádriceps / Glúteos', equip:'Peso corporal',
    setup:'De pie, pies a la anchura de hombros, brazos al frente para equilibrio.',
    tip:'Bajá sacando la cola hasta muslos paralelos, subí con los talones. Hacela lenta para más intensidad.' },
  'Step-up_with_Knee_Raise': { es:'Subida al escalón con rodilla', musc:'Piernas / Glúteos', equip:'Peso corporal',
    setup:'Usá un escalón o banco firme. Subí con una pierna.',
    tip:'Subí empujando con el talón y elevá la rodilla contraria arriba. Alterná.' },
  'Monster_Walk': { es:'Caminata lateral con banda', musc:'Glúteo medio', equip:'Liga cerrada',
    setup:'Liga cerrada alrededor de los tobillos o arriba de las rodillas. Media sentadilla, pies separados para tensar la liga.',
    tip:'Caminá de lado dando pasos firmes sin juntar los pies. Mantené la tensión todo el tiempo.' },
  'Side_Leg_Raises': { es:'Elevación lateral de pierna con banda', musc:'Glúteo medio / Abductor', equip:'Liga cerrada',
    setup:'Liga cerrada arriba de los tobillos. De pie sujetándote de algo, o acostada de lado.',
    tip:'Llevá la pierna hacia el costado contra la liga apretando el glúteo. Bajá lento. Alterná.' },
  'Band_Hip_Adductions': { es:'Abducción de cadera con banda', musc:'Glúteo medio / Abductor', equip:'Liga cerrada',
    setup:'Liga cerrada arriba de las rodillas. Acostada de lado o sentada con las rodillas flexionadas.',
    tip:'Abrí las rodillas contra la liga (tipo “almeja”) apretando el glúteo, cerrá controlando.' },
  'Glute_Kickback': { es:'Patada de glúteo con banda', musc:'Glúteos', equip:'Liga cerrada',
    setup:'En cuatro apoyos (manos y rodillas). Liga cerrada alrededor de los pies/tobillos.',
    tip:'Llevá una pierna hacia atrás-arriba estirándola contra la liga, apretá el glúteo. Alterná.' },
  'Rear_Leg_Raises': { es:'Elevación de pierna hacia atrás', musc:'Glúteos', equip:'Liga cerrada',
    setup:'De pie sujetándote de algo firme. Liga cerrada arriba de los tobillos.',
    tip:'Llevá una pierna recta hacia atrás apretando el glúteo, sin arquear la espalda. Alterná.' },
};

/* Warmup (calentamiento) por día */
const WARM = {
  torso: ['5 min de bici o elíptico suave', 'Círculos de brazos y hombros 30 s', '1 serie liviana del primer ejercicio (15 reps)'],
  pierna: ['5 min de bici o caminadora', 'Sentadillas sin peso 15 reps', 'Movilidad de cadera y tobillo 1 min', '1 serie liviana de sentadilla/prensa'],
};

/* ============================================================
   RUTINA · 4 días · sin abdomen
   Cada ejercicio: opts (alternativas para cambiar), sets, reps,
   rest (seg), lb (peso inicial sugerido en libras, editable),
   inc (cuánto subir cuando fue "fácil")
   ============================================================ */
const ROUTINE = {
  version: 1,
  title: 'Rutina de Hipertrofia · 4 días',
  days: [
    {
      id: 'd1', name: 'Día 1', focus: 'Pecho y Tríceps', emoji: '💪', warm: 'torso',
      exercises: [
        { key:'d1e1', name:'Press de pecho', opts:['Barbell_Bench_Press_-_Medium_Grip','Dumbbell_Bench_Press','Machine_Bench_Press'], sets:4, reps:'8–12', rest:120, lb:45, inc:10 },
        { key:'d1e2', name:'Press inclinado', opts:['Incline_Dumbbell_Press','Machine_Bench_Press'], sets:3, reps:'10–12', rest:90, lb:25, inc:5 },
        { key:'d1e3', name:'Aperturas / Contractora', opts:['Butterfly','Cable_Crossover','Dumbbell_Flyes'], sets:3, reps:'12–15', rest:75, lb:40, inc:5 },
        { key:'d1e4', name:'Extensión de tríceps en polea', opts:['Triceps_Pushdown','Triceps_Pushdown_-_Rope_Attachment','Reverse_Grip_Triceps_Pushdown'], sets:4, reps:'10–15', rest:60, lb:30, inc:5 },
        { key:'d1e5', name:'Tríceps sobre la cabeza', opts:['EZ-Bar_Skullcrusher','Cable_Rope_Overhead_Triceps_Extension','Standing_Dumbbell_Triceps_Extension'], sets:3, reps:'10–12', rest:75, lb:30, inc:5 },
      ],
    },
    {
      id: 'd2', name: 'Día 2', focus: 'Espalda y Bíceps', emoji: '🔙', warm: 'torso',
      exercises: [
        { key:'d2e1', name:'Jalón al pecho', opts:['Wide-Grip_Lat_Pulldown','Close-Grip_Front_Lat_Pulldown'], sets:4, reps:'10–12', rest:90, lb:50, inc:10 },
        { key:'d2e2', name:'Remo sentado en polea', opts:['Seated_Cable_Rows','Bent_Over_Two-Dumbbell_Row'], sets:4, reps:'10–12', rest:90, lb:50, inc:10 },
        { key:'d2e3', name:'Remo con barra/mancuernas', opts:['Bent_Over_Barbell_Row','Bent_Over_Two-Dumbbell_Row'], sets:3, reps:'8–12', rest:90, lb:45, inc:5 },
        { key:'d2e4', name:'Curl con barra', opts:['Barbell_Curl','EZ-Bar_Curl'], sets:4, reps:'8–12', rest:60, lb:30, inc:5 },
        { key:'d2e5', name:'Curl martillo', opts:['Hammer_Curls','Alternate_Hammer_Curl','Cable_Hammer_Curls_-_Rope_Attachment'], sets:3, reps:'10–12', rest:60, lb:15, inc:5 },
      ],
    },
    {
      id: 'd3', name: 'Día 3', focus: 'Piernas', emoji: '🦵', warm: 'pierna',
      exercises: [
        { key:'d3e1', name:'Sentadilla / Prensa', opts:['Barbell_Squat','Leg_Press'], sets:4, reps:'8–12', rest:150, lb:45, inc:10 },
        { key:'d3e2', name:'Prensa de piernas', opts:['Leg_Press','Narrow_Stance_Leg_Press'], sets:4, reps:'10–15', rest:120, lb:90, inc:10 },
        { key:'d3e3', name:'Extensión de cuádriceps', opts:['Leg_Extensions'], sets:3, reps:'12–15', rest:75, lb:40, inc:10 },
        { key:'d3e4', name:'Curl femoral', opts:['Lying_Leg_Curls','Seated_Leg_Curl'], sets:4, reps:'10–12', rest:75, lb:40, inc:10 },
        { key:'d3e5', name:'Peso muerto rumano', opts:['Romanian_Deadlift'], sets:3, reps:'10–12', rest:120, lb:45, inc:10 },
        { key:'d3e6', name:'Gemelos', opts:['Standing_Calf_Raises','Calf_Press'], sets:4, reps:'15–20', rest:60, lb:60, inc:10 },
      ],
    },
    {
      id: 'd4', name: 'Día 4', focus: 'Hombros y Brazos', emoji: '🏔️', warm: 'torso',
      exercises: [
        { key:'d4e1', name:'Press de hombros', opts:['Dumbbell_Shoulder_Press','Standing_Dumbbell_Press','Smith_Machine_Overhead_Shoulder_Press'], sets:4, reps:'8–12', rest:90, lb:20, inc:5 },
        { key:'d4e2', name:'Elevaciones laterales', opts:['Side_Lateral_Raise'], sets:4, reps:'12–15', rest:60, lb:10, inc:5 },
        { key:'d4e3', name:'Hombro posterior', opts:['Face_Pull','Reverse_Machine_Flyes','Cable_Rear_Delt_Fly'], sets:3, reps:'12–20', rest:60, lb:25, inc:5 },
        { key:'d4e4', name:'Elevaciones frontales', opts:['Front_Dumbbell_Raise'], sets:3, reps:'12–15', rest:60, lb:10, inc:5 },
        { key:'d4e5', name:'Curl de bíceps', opts:['EZ-Bar_Curl','Barbell_Curl','Cable_Hammer_Curls_-_Rope_Attachment'], sets:3, reps:'10–12', rest:60, lb:30, inc:5 },
        { key:'d4e6', name:'Tríceps en polea', opts:['Triceps_Pushdown_-_Rope_Attachment','Triceps_Pushdown','Reverse_Grip_Triceps_Pushdown'], sets:3, reps:'12–15', rest:60, lb:30, inc:5 },
      ],
    },
  ],
};

/* ============================================================
   RUTINA EN CASA / VIAJE · bandas, pelota, mancuernas livianas
   Pesos en el mismo campo (poné tu kg o ignoralo en bandas)
   ============================================================ */
const ROUTINE_CASA = {
  version: 1,
  title: 'En casa · 4 días',
  days: [
    {
      id: 'c1', name: 'Día 1', focus: 'Pecho y Tríceps', emoji: '💪', warm: 'torso',
      exercises: [
        { key:'c1e1', name:'Press de pecho', opts:['Dumbbell_Bench_Press','Bench_Press_-_With_Bands'], sets:4, reps:'10–12', rest:90, lb:11, inc:2 },
        { key:'c1e2', name:'Flexiones', opts:['Pushups'], sets:3, reps:'8–15', rest:60, lb:0, inc:0 },
        { key:'c1e3', name:'Aperturas', opts:['Dumbbell_Flyes'], sets:3, reps:'12–15', rest:60, lb:5, inc:2 },
        { key:'c1e4', name:'Rompecráneos', opts:['Band_Skull_Crusher','Standing_Dumbbell_Triceps_Extension'], sets:3, reps:'12–15', rest:60, lb:5, inc:2 },
        { key:'c1e5', name:'Patada de tríceps', opts:['Tricep_Dumbbell_Kickback'], sets:3, reps:'12–15', rest:60, lb:5, inc:2 },
      ],
    },
    {
      id: 'c2', name: 'Día 2', focus: 'Espalda y Bíceps', emoji: '🔙', warm: 'torso',
      exercises: [
        { key:'c2e1', name:'Remo a un brazo', opts:['One-Arm_Dumbbell_Row'], sets:4, reps:'10–12', rest:90, lb:11, inc:2 },
        { key:'c2e2', name:'Remo con mancuernas', opts:['Bent_Over_Two-Dumbbell_Row'], sets:3, reps:'10–12', rest:75, lb:11, inc:2 },
        { key:'c2e3', name:'Pull apart con banda', opts:['Band_Pull_Apart'], sets:3, reps:'15–20', rest:60, lb:0, inc:0 },
        { key:'c2e4', name:'Pullover', opts:['Bent-Arm_Dumbbell_Pullover'], sets:3, reps:'12–15', rest:60, lb:11, inc:2 },
        { key:'c2e5', name:'Curl de bíceps', opts:['Dumbbell_Bicep_Curl','Hammer_Curls'], sets:4, reps:'10–12', rest:60, lb:5, inc:2 },
        { key:'c2e6', name:'Curl martillo', opts:['Hammer_Curls','Alternate_Hammer_Curl'], sets:3, reps:'12–15', rest:60, lb:5, inc:2 },
      ],
    },
    {
      id: 'c3', name: 'Día 3', focus: 'Piernas y Glúteos', emoji: '🦵', warm: 'pierna',
      exercises: [
        { key:'c3e1', name:'Sentadilla', opts:['Dumbbell_Squat','Squats_-_With_Bands'], sets:4, reps:'10–15', rest:90, lb:11, inc:2 },
        { key:'c3e2', name:'Zancadas', opts:['Dumbbell_Lunges'], sets:3, reps:'10–12', rest:75, lb:5, inc:2 },
        { key:'c3e3', name:'Peso muerto rumano', opts:['Stiff-Legged_Dumbbell_Deadlift'], sets:4, reps:'10–12', rest:90, lb:11, inc:2 },
        { key:'c3e4', name:'Sentadilla sumo', opts:['Plie_Dumbbell_Squat'], sets:3, reps:'12–15', rest:60, lb:11, inc:2 },
        { key:'c3e5', name:'Puente de glúteos', opts:['Butt_Lift_Bridge','Single_Leg_Glute_Bridge','Physioball_Hip_Bridge'], sets:3, reps:'12–20', rest:60, lb:0, inc:0 },
        { key:'c3e6', name:'Extensión de cadera con banda', opts:['Hip_Extension_with_Bands'], sets:3, reps:'15–20', rest:45, lb:0, inc:0 },
        { key:'c3e7', name:'Gemelos con banda', opts:['Calf_Raises_-_With_Bands'], sets:4, reps:'15–20', rest:45, lb:0, inc:0 },
      ],
    },
    {
      id: 'c4', name: 'Día 4', focus: 'Hombros y Brazos', emoji: '🏔️', warm: 'torso',
      exercises: [
        { key:'c4e1', name:'Press de hombros', opts:['Dumbbell_Shoulder_Press','Arnold_Dumbbell_Press'], sets:4, reps:'8–12', rest:90, lb:5, inc:2 },
        { key:'c4e2', name:'Elevaciones laterales', opts:['Seated_Side_Lateral_Raise','Lateral_Raise_-_With_Bands','One-Arm_Side_Laterals'], sets:4, reps:'12–15', rest:60, lb:4, inc:2 },
        { key:'c4e3', name:'Hombro posterior', opts:['Reverse_Flyes','Band_Pull_Apart'], sets:3, reps:'15–20', rest:60, lb:4, inc:2 },
        { key:'c4e4', name:'Curl de bíceps', opts:['Dumbbell_Bicep_Curl'], sets:3, reps:'10–12', rest:60, lb:5, inc:2 },
        { key:'c4e5', name:'Patada de tríceps', opts:['Tricep_Dumbbell_Kickback','Band_Skull_Crusher'], sets:3, reps:'12–15', rest:60, lb:5, inc:2 },
      ],
    },
  ],
};

/* ============================================================
   RUTINA BARCO · ligas cerradas chiquitas (tipo pilates) + peso corporal
   Sin pesos ni ligas largas. Arriba: peso corporal. Abajo: liga cerrada.
   ============================================================ */
const ROUTINE_BARCO = {
  version: 2,
  title: 'Barco · 4 días',
  days: [
    {
      id: 'b1', name: 'Día 1', focus: 'Pecho y Tríceps', emoji: '💪', warm: 'torso',
      exercises: [
        { key:'b1e1', name:'Flexiones', opts:['Pushups'], sets:4, reps:'8–15', rest:75, lb:0, inc:0 },
        { key:'b1e2', name:'Flexiones inclinadas', opts:['Incline_Push-Up'], sets:3, reps:'10–15', rest:60, lb:0, inc:0 },
        { key:'b1e3', name:'Flexiones diamante', opts:['Close-Grip_Push-Up_off_of_a_Dumbbell'], sets:3, reps:'8–12', rest:60, lb:0, inc:0 },
        { key:'b1e4', name:'Fondos de tríceps', opts:['Bench_Dips'], sets:4, reps:'8–15', rest:60, lb:0, inc:0 },
      ],
    },
    {
      id: 'b2', name: 'Día 2', focus: 'Espalda y Hombros', emoji: '🔙', warm: 'torso',
      exercises: [
        { key:'b2e1', name:'Flexiones pica (hombros)', opts:['Handstand_Push-Ups'], sets:4, reps:'6–12', rest:75, lb:0, inc:0 },
        { key:'b2e2', name:'Superman', opts:['Superman'], sets:3, reps:'12–15', rest:60, lb:0, inc:0 },
        { key:'b2e3', name:'Extensión de espalda', opts:['Hyperextensions_With_No_Hyperextension_Bench'], sets:3, reps:'12–15', rest:60, lb:0, inc:0 },
        { key:'b2e4', name:'Pull apart con banda', opts:['Band_Pull_Apart'], sets:3, reps:'15–20', rest:60, lb:0, inc:0 },
        { key:'b2e5', name:'Rotación externa con banda', opts:['External_Rotation_with_Band'], sets:3, reps:'15–20', rest:45, lb:0, inc:0 },
      ],
    },
    {
      id: 'b3', name: 'Día 3', focus: 'Piernas y Glúteos', emoji: '🦵', warm: 'pierna',
      exercises: [
        { key:'b3e1', name:'Sentadilla con banda', opts:['Squats_-_With_Bands','Bodyweight_Squat'], sets:4, reps:'12–20', rest:75, lb:0, inc:0 },
        { key:'b3e2', name:'Subida al escalón', opts:['Step-up_with_Knee_Raise'], sets:3, reps:'10–12', rest:60, lb:0, inc:0 },
        { key:'b3e3', name:'Caminata lateral con banda', opts:['Monster_Walk'], sets:3, reps:'12–15', rest:45, lb:0, inc:0 },
        { key:'b3e4', name:'Puente de glúteos', opts:['Butt_Lift_Bridge','Single_Leg_Glute_Bridge'], sets:3, reps:'12–20', rest:60, lb:0, inc:0 },
        { key:'b3e5', name:'Patada de glúteo con banda', opts:['Glute_Kickback'], sets:3, reps:'12–15', rest:45, lb:0, inc:0 },
        { key:'b3e6', name:'Gemelos', opts:['Calf_Raises_-_With_Bands'], sets:4, reps:'15–20', rest:45, lb:0, inc:0 },
      ],
    },
    {
      id: 'b4', name: 'Día 4', focus: 'Glúteos y Piernas', emoji: '🍑', warm: 'pierna',
      exercises: [
        { key:'b4e1', name:'Sentadilla libre', opts:['Bodyweight_Squat','Squats_-_With_Bands'], sets:4, reps:'15–20', rest:60, lb:0, inc:0 },
        { key:'b4e2', name:'Abducción de cadera con banda', opts:['Band_Hip_Adductions'], sets:3, reps:'15–20', rest:45, lb:0, inc:0 },
        { key:'b4e3', name:'Extensión de cadera con banda', opts:['Hip_Extension_with_Bands'], sets:3, reps:'12–15', rest:45, lb:0, inc:0 },
        { key:'b4e4', name:'Elevación lateral de pierna', opts:['Side_Leg_Raises'], sets:3, reps:'15–20', rest:45, lb:0, inc:0 },
        { key:'b4e5', name:'Elevación de pierna atrás', opts:['Rear_Leg_Raises'], sets:3, reps:'15–20', rest:45, lb:0, inc:0 },
        { key:'b4e6', name:'Puente a una pierna', opts:['Single_Leg_Glute_Bridge','Butt_Lift_Bridge'], sets:3, reps:'12–15', rest:45, lb:0, inc:0 },
      ],
    },
  ],
};
